default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: p_1_development

test:
  <<: *default
  database: p_1_test

production:
  <<: *default
  database: p_1_production
  username: p_1
  password: <%= ENV['P_1_DATABASE_PASSWORD'] %>
